# 这是一个基本的工作流程，可以帮助您开始行动

name: 'github actions publish x-cmd/dev'

# 控制工作流何时运行
on:
  # 在推送或拉送请求事件上触发工作流，但仅适用于主分支
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:

# 工作流运行由一个或多个可以顺序或并行运行的作业组成
jobs:
  # 此工作流包含一个名为“bot”的作业
  bot:
    # 作业将在其上运行的运行程序类型
    runs-on: ubuntu-latest

    # 步骤表示将作为作业一部分执行的任务序列
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: install x-cmd && setup ssh publish
      # 在$GITHUB_WORKSPACE下检查您的存储库，以便您的作业可以访问它
        uses: cycle886/helloworld_action@main
        with:
          who_say_hello: cycle886
        #   sshkey: ${{ secrets.SSH_PRIVATE_KEY }}
        #   user/email: agent-zero/0@x-cmd.com
        # run: xws pub

      #使用runners外壳运行单个命令
      # - name: Run x-cmd
      #   run: x ls

      # 使用runners外壳运行一组命令
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
      - name: commit
        run: |
          pwd
          git config --global user.email 1096481521@qq.com
          git config --global user.name cycle886
          git add .
          git commit -m "update" -a
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

